# Generated by Django 4.0.4 on 2022-05-13 13:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 9, 14, 113393, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('site_contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('lang', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=25)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 9, 14, 114127, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=25)),
                ('main_color', models.CharField(max_length=25)),
                ('full_site_color', models.CharField(max_length=25)),
                ('default', models.BooleanField()),
                ('copy_rigtht', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SliderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.CharField(max_length=25)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('photo_profile', models.ImageField(upload_to='')),
                ('data_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.district')),
            ],
        ),
    ]
