# Generated by Django 4.0.4 on 2022-05-13 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 9, 46, 313853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='district',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 9, 46, 314441, tzinfo=utc)),
        ),
    ]
