# Generated by Django 4.0.4 on 2022-05-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersite',
            name='photo_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.photoprofile'),
        ),
        migrations.AddField(
            model_name='service',
            name='photo_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.photoprofile'),
        ),
    ]
