# Generated by Django 4.0.4 on 2022-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_client_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofile',
            name='photo_profile',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
