# Generated by Django 4.0.4 on 2022-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_photoprofile_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo_profile',
            field=models.ImageField(upload_to=''),
        ),
    ]
